version: "3.8"
services:
  dev-database:
    image: postgres:15.0
    container_name: first-project-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: firstdb
    networks:
      - nestjs-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - nestjs-network

networks:
  nestjs-network:
